name: "T's Startup Ideas"
favicon: null
layout_spectrum: 0.42302275309339166
typography_spectrum: 0.6421058301348239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.10743293701671064
  lightness: 0.7504612160846591
  saturation: 0.6279529561288655
  rhythmicContrast: 0.10168905113823712
purpose: []
